baseURL = "https://blog.calinp.dev/"
author = "Calin-Petru"
copyright = "Copyright © 2024, all rights reserved."
paginate = 3
languageCode = "en-US"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "hugo-theme-console"
title = "Calin's DevBlog"

titleCutting = false
animateStyle = "animated zoomIn fast" 
[params]
  color = 'linen'

  github = 'Ardelean-Calin'

  avatar = 'calinp@duck.com'
  name = 'Călin'
  bio = 'Embedded Software and Hardware Engineer'

  enablePhotos = false

[params.umami]
  enabled = true
  websiteId = "ce37afb9-aa01-41df-a0d4-41e53dd30bd4"
  jsLocation = "https://umami.calin.cloud/script.js"

[[params.navlinks]]
  name = "about/"
  url = "about/"

[[params.navlinks]]
  name = "posts/"
  url = "posts/"
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
